.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "YAML" "1" "December 2012" "" ""
.
.SH "NAME"
\fByaml\fR \- yaml command
.
.SH "SYNOPSIS"
\fByaml [command] [options] [arguments]\fR
.
.SH "DESCRIPTION"
The yaml command is a command line tool for working wiuth YAML files\.
.
.SH "COMMAND"
The following are the various subcommands currently supported by the yaml command:
.
.IP "\(bu" 4
\fBget <YPATH>\fR The \fBget\fR command simply extracts a portion of a YAML file and outputs it to stdout\.
.
.IP "\(bu" 4
\fBset <YPATH> <VALUE>\fR The \fBset\fR commnd is the opposite of \fBget\fR in that it lets you change a portion of a YAML file\. By defult the changed YAML document will go to stdout, using the \fB\-s/\-\-save\fR option rewrites the file with the change\.
.
.IP "\(bu" 4
\fBsort\fR The \fBsort\fR command can be used to sort portions of a YAML document\.
.
.IP "\(bu" 4
\fBslurp <DIR>\fR The \fBslurp\fR command takes a directory and converts it\'s contents into a YAML file\.
.
.IP "\(bu" 4
\fBsplat <DIR>\fR The \fBsplat\fR command take a YAML file and converts it into a file directory structure\. It is essentially the opposite of slurp\.
.
.IP "\(bu" 4
\fBedit\fR The \fBedit\fR command will open a YAML file for editing in the default editor (as defined by $EDITOR), and allow you to edit it\.
.
.IP
If instead you edit a directory, then the directory will be automatically slurped into a temporary file\. After editing the temporary file will be splatted back out to update the directory and it\'s files\.
.
.IP "\(bu" 4
\fBview\fR The \fBview\fR command prints a colorized rendering of the YAML file\.
.
.IP "" 0
.
.SH "SEE ALSO"
yaml\-get(1), yaml\-set(1), yaml\-sort(1), yaml\-slurp(1), yaml\-splat(1), yaml\-edit(1), yaml\-view(1)
