.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "YAML\-GET" "1" "December 2012" "" ""
.
.SH "NAME"
\fByaml\-get\fR \- yaml get command
.
.SH "SYNOPSIS"
\fByaml get [options] [ypath]\fR
.
.SH "DESCRIPTION"
Extract values from a YAML document given a YPath\.
.
.SH "OPTIONS"
Note that not all formats support all options, and some formats use them in variant manners\.
.
.IP "\(bu" 4
\fB\-F\fR/\fB\-\-file\fR \fIPATH\fR The YAML file to query, if not by stdin\.
.
.IP "\(bu" 4
\fB\-y\fR/\fB\-\-yaml\fR Produce output in YAML format\.
.
.IP "\(bu" 4
\fB\-j\fR/\fB\-\-json\fR Produce output in JSON format\.
.
.IP "" 0
.
.SH "SEE ALSO"
yaml(1), yaml\-set(1), yaml\-sort(1), yaml\-slurp(1), yaml\-splat(1), yaml\-edit(1), yaml\-view(1)
